apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'

android {
    compileSdk 35

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 35

        consumerProguardFiles 'consumer-rules.pro'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
        qa {
            minifyEnabled false
        }
    }

    buildFeatures {
        viewBinding true
    }
    namespace 'pl.lejdi.filebrowserfragment'
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.15.0'

    //layouts
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'

    //recyclerview
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
}
